[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
# Use 9mBrgXgC6v5a6oBvs7amcCTkeDohadP8ZmP5CikV3qvT for local testing
universal_gateway = "CFVSincHYbETh2k7w6u1ENEkjbSLtveRCEBupKidw2VS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./upgrade-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.test.ts"

[test]
startup_wait = 10000
shutdown_wait = 5000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
rpc_port = 8899
ledger = ".anchor/test-ledger"
reset = true
