[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
# Use DJoFYDpgbTfxbXBv1QYhYGc9FK4J5FUKpYXAfSkHryXp for local testing
universal_gateway = "DJoFYDpgbTfxbXBv1QYhYGc9FK4J5FUKpYXAfSkHryXp"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "https://api.devnet.solana.com"
wallet = "./upgrade-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.test.ts"

[test]
startup_wait = 10000
shutdown_wait = 5000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
rpc_port = 8899
ledger = ".anchor/test-ledger"
reset = true

[[test.genesis]]
address = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
program = "tests/fixtures/pyth_pull.so"
upgradeable = true
